changes for production mode
uclibs/uc_drc pull request #108
Opened 2021-01-26 03:07 UTC by crowesn

Fixes #69 

Add config changes to run application in production mode.

Changes proposed in this pull request:
* config production values
* Add dotenv variables for production mode
* Add readme entry about docker production mode

2021-01-26 16:42 UTC, crowesn commented
Probably best to test manually on local machine

Production mode: `RAILS_ENV=production docker-compose up -d --build`
Development mode: `docker-compose up -d --build`

I don't think you should need to clear the data between tests but you can stop the app with `docker-compose down` to retain data and `docker-compose down -v` to delete the data.

2021-01-27 02:06 UTC, hortongn requested changes
@crowesn I had to make a couple tweaks to the puma.rb to get the site to load for me.  See my comments inline.  We can discuss if those suggestions don't make sense.

2021-01-27 02:06 UTC, hortongn commented on config/puma.rb
> +  port ENV.fetch('PORT', 3010)
I think this should be 3000 not 3010.

2021-01-29 19:37 UTC, hortongn approved these changes
@crowesn Works great.  Nice job!

2021-01-29 19:37 UTC, merged