add docker spec env vars
uclibs/uc_drc pull request #112
Opened 2021-02-01 19:53 UTC by crowesn

Fixes #95 
Present short summary (50 characters or less)

Add db_test container and test environment variables for running specs in docker

Changes proposed in this pull request:
* Add db_test container to docker-compose.yml
* Add .env.test environment variables
* Update readme

2021-02-10 20:57 UTC, scherztc approved these changes

2021-02-10 20:58 UTC, scherztc commented
@crowesn It looks like the delay caught a conflicting file.  Any chance you could resolve the conflict?

2021-02-10 23:02 UTC, scherztc requested changes
Fix the file conflict and we can merge it.

2021-02-15 20:09 UTC, crowesn commented
@scherztc done!

2021-02-15 22:40 UTC, scherztc approved these changes

2021-02-15 22:41 UTC, merged